### ISSUE TITLE
Any way to get the actual version?

### ISSUE THREAD

**Issue by bitbaggi** [Nightapes/go-semantic-release#34]

**Comment by Nightapes** [comment]
You can download here https://github.com/Nightapes/go-semantic-release/releases
Or you can use docker https://hub.docker.com/r/nightapes/go-semantic-release/tags

But i will add a description to the readme

**Comment by bitbaggi** [comment]
Oh, sorry i mean, how can i get the actual version with this.
'./go-semantic-release next' returns only the next version, not the actual.

**Comment by Nightapes** [comment]
See #35
