### ISSUE TITLE
Creates no release when merges merge requests

### ISSUE THREAD

**Issue by bitbaggi** [Nightapes/go-semantic-release#36]
Hi,

when i create a merge request and merge this, then no new release is created.

```
feature-branch-commits:
fix(*): fixed ...

development-commits after merge:
Merge feature-branch-commits into development.


Creates no release.
```
```
direct commit to development with message fix(*): fixed... 

creates release
```

Expected:
```
Commit Message "Merge feature-branch-commits into development" should create an release.
```
If no fix/feat commit is in commit list, create default release message

**Comment by Nightapes** [comment]
Hi, do you have a example repository? 

When i merge a pull request it's working, see https://github.com/Nightapes/go-semantic-release/commits/master

**Comment by fwiedmann** [comment]
Closing this issue. The CI/CD Platform of @bitbaggi  did not included all git commits during CI runs.
