### ISSUE TITLE
Add a possibility to choose the version tag format (make prefix optional)

### ISSUE THREAD

**Issue by maulik13** [Nightapes/go-semantic-release#47]
Right now the version tag prefix is hardcoded here: https://github.com/Nightapes/go-semantic-release/blob/master/internal/releaser/github/github.go#L93

It would be very helpful to move this to the configuration file.

**Comment by maulik13** [comment]
@Nightapes  if you want I can make a pull request for this. Please let me know.

**Comment by fwiedmann** [comment]
@maulik13 hey thank you for your suggestion. Sure PRs are welcome.

**Comment by maulik13** [comment]
It would be great, if this can be merged (given changes are approved). We need this feature since our version tags are not prefixed in the existing projects. 

Thanks.
