### ISSUE TITLE
Follow the commit structure with subject, body, footer in the parsed commit message 

### ISSUE THREAD

**Issue by maulik13** [Nightapes/go-semantic-release#56]
At the moment, analyzer only parses the message in to two fields `ParsedMessage` and `ParsedBreakingChangeMessage`. Commit messages with a body and a footer are then not rendered nicely in the changelog. If the commit analyzer would parse the messages to follow the commit structure (see blow) and populate the fields (`type`, `subject`, `body`, `footer`) that would make it much easier to render them in a changelog. The subject line will always be used as a bullet point and body/footer can be rendered as a sub point or a note. 

Both conventional commits and angular project define the following structure for the commit messages. 

```
<type>(<scope>): <subject>

<body>

<footer>
```

**Comment by maulik13** [comment]
I can get on this PR, since we need this feature in our team.

**Comment by maulik13** [comment]
Angular convention and conventional-commit both have the same structure. But in order to provide a generic structure that could work for different analyzers I think we could still use `header`, `body` and `footer` sections. However, it is possible to have multiples body blocks or footers for including extra information in the commit messages. For example, [using git trailers format](https://git-scm.com/docs/git-interpret-trailers). Any thoughts on that?

**Comment by fwiedmann** [comment]
Just for my understanding, this is what you think of, right?
```
feat(foo): bar // header
Note: foo bar // body 1 with prefix
Note: foo bar // body 2 with prefix

BREAKING CHANGE: bar foo // footer
```

The changelog:

```
- feat(foo): bar 
  - Note: foo bar
  - Note: foo bar 
```

I think this would be good improvement. I like the idea of listing the body section as bullet points for a header.
@Nightapes What are your thoughts?

**Comment by maulik13** [comment]
Yes, close to what I was thinking. And I have also added a map function in the previous changelog PR to deal with multi-line notes. A note can also be multi-line like this:

```
feat(foo): new feature for foo

Note: This new feature will provide the following items:
- Item 1
- Item 2
```

I have a draft ready that  handles the logic for the 3 section structure, but as I mentioned it would be better to use a generic structure instead of just header, body and footer.

**Comment by fwiedmann** [comment]
So the more generic solution would be adding []bodySection for the Body and and a rule to detect a section by a newline + a prefix? And to remove the footer? So that the analyzer is responsible to notice that kind of section.

**Comment by maulik13** [comment]
I think that is a correct interpretation of what I meant. But just to be clear here is a concrete structure. 

```
type AnalyzedCommit struct {
    Commit                      Commit 
    Scope                       Scope 
    Tag                         string 
    TagString                   string 
    Subject                     string 
    Sections                 map[string][]MessageSection
    IsBreaking                  bool  
    Print                       bool   
}

type MessageSection struct {
    Label     string
    Content    string  
}
```

`map[string]MessageSection` will have key used as a section type (body, footer etc...). So let's take the following message as an example. 

```
feat(api): add new endpoint to edit metadata for all entities

Note: The following metadata fields are supported for the entities
- *revision* : holds the version number of the entitiy
- *modified_at*: shows when the entity was modified

Jira-Issue: WA-1234
Asana-TaskId: ab43cd
```

After decoding this you will get the following for map[string][]MessageSection:
```
{
  "body": [{
      "label" : "Note",
      "content": "This new feature will provide the following items: \n- Item 1\n- Item 2"
    }
  ],
  "footer": [{
      "label" : "Jira-Issue",
      "content": "WD-1234"
    },
    {
      "label": "Asana-TaskId",
      "content": "ab43cd"
    }
  ]
}
```

This way an analyzer can decide how to decode a commit message. It can decide to categorize sections or not. Any sections without a label (e.g. Note: ) can also be decoded (or not depending on config). 

I hope this is clear enough :)

**Comment by fwiedmann** [comment]
For me this is fine. So do you want to update your draft for this generic version?

**Comment by maulik13** [comment]
Great! I will make a PR using this concept then. Just one more question, how do you guys feel about keeping backward-compatibility? I have it in my mind, but wanted to check with you.

**Comment by maulik13** [comment]
I have left the previous variables for backward compatibility for now.

**Comment by fwiedmann** [comment]
Perfect

**Comment by maulik13** [comment]
It has taken some time, but I have finally made a PR for this issue #61. Please have a look. It has a lot of changes so if you have question please let me know. I have written a summary of changes in the PR description.

**Comment by maulik13** [comment]
Closing this since PR is merged.
