### ISSUE TITLE
release 1.9.0: message block does not have the same indents

### ISSUE THREAD

**Issue by fwiedmann** [Nightapes/go-semantic-release#62]
I realized that a message block in a changelog does not has the same indent as the headers or footers in a commit. For better readability, I suggest adding spaces to the message block until it aligns with the bullet points, the same for the footer bullet points. I also suggest adding a line break between the header and the message block.

We could use direct HTML templates instead of using markdown.

Quickfix: Adding HTML spaces in the markdown using `&nbsp;`:

## Features

- angular update angular to include new structured fields (7208dae)

- conventional parse body and footers according to the rules

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Previous assumption about multiple labeled body blocks and footers is
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;not correct. There is only one body text block with multi-line support.
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;A footer always starts with a token with a separator.

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;- A body ends when a footer is found or text ends.
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;- A footer ends when another footer is found or text ends. (a20992a)
- analyzer update AnalyzedCommit to add flexibility in parsing a message

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;This provides flexibility of parsing and rendering structured messages
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;with more detail in the changelog and helps extract metadata from the
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;message. The new structure can be used to split a message in multiple
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;blocks (e.g. footer) (dc4d1c5)

**Comment by fwiedmann** [comment]
@maulik13 @Nightapes  what do you think? 😄

**Comment by maulik13** [comment]
Have you looked at helper function `addPrefixToLines` in[ changelog.go](https://github.com/Nightapes/go-semantic-release/blob/master/internal/changelog/changelog.go#L227-L235)? Depending on how you want to nest things you can use that function to add indentation. I use it like this in my template:

```
...
{{ with .MessageBlocks.body -}}
{{ $bodyBlock := index . 0 }} 
{{ addPrefixToLines  $bodyBlock.Content "  > "}}
{{ end -}}
...
```

Perhaps we could just update the default changelog template?
